test:
  secret_key_base: <%= Rails.application.credentials.test[:secret_key_base] %>
  name: <%= Rails.application.credentials.test[:database][:name] %>
  username: <%= Rails.application.credentials.test[:database][:username] %>
  password: <%= Rails.application.credentials.test[:database][:password] %>

development:
  secret_key_base: <%= Rails.application.credentials.development[:secret_key_base] %>
  name: <%= Rails.application.credentials.development[:database][:name] %>
  username: <%= Rails.application.credentials.development[:database][:username] %>
  password: <%= Rails.application.credentials.development[:database][:password] %>